### ISSUE TITLE
Drag and drop con fondo blanco

### ISSUE THREAD

**Issue by Ian2012** [eduNEXT/ednx-saas-themes#131]
La siguiente regla CSS configura con fondo blanco los problemas de tipo drag-and-drop:

```css
.dashboard .my-courses, .dashboard .main-container, .dashboard .main-container .my-courses .listing-courses .course-item, .dashboard .main-container .my-courses .listing-courses .course-item .course-container, .dashboard .main-container .my-courses .course .details, .dashboard .main-container .my-courses .course, .account-settings-tabpanels .section, .account-settings-section-body, .account-settings-sections .section .account-settings-section-body .u-field, .course-tool-link, .course-outline ol.outline-item .subsection .vertical a, .problems-wrapper, .xblock-student_view-problem.xmodule_display, .choicegroup.capa_inputtype, .problem div:not([id*="answer"]) {
    background-color: #fff; 
}
```
Resultado:
![image](https://user-images.githubusercontent.com/33465240/212192194-07a085aa-343f-4d6b-8a4b-a0284ea61196.png)

Regla desacitvada:

![image](https://user-images.githubusercontent.com/33465240/212192239-f7ce3f66-728b-4c45-b015-dee521394161.png)
